# Configuration for running Cortex in single-process mode.
# This should not be used in production.  It is only for getting started
# and development.

# Comma-separated list of Cortex modules to load. The alias 'all' can be used in
# the list to load a number of core modules and will enable single-binary mode.
# Use '-modules' command line flag to get a list of available modules, and to
# see which modules are included in 'all'.
# CLI flag: -target
target: "distributor"

# Disable the requirement that every request to Cortex has a
# X-Scope-OrgID header. `fake` will be substituted in instead.
auth_enabled: false

# The server_config configures the HTTP and gRPC server of the launched
# service(s).
server:  
  # HTTP server listen port.
  # CLI flag: -server.http-listen-port
  http_listen_port: 9009

  # Only log messages with the given severity or above. Valid levels: [debug, info, warn, error]
  # CLI flag: -log.level
  log_level: "error"

  # Output log messages in the given format. Valid formats: [logfmt, json]
  # CLI flag: -log.format
  log_format: "json"

  # Configure the server to allow messages up to 100MB.
  grpc_server_max_recv_msg_size: 104857600
  grpc_server_max_send_msg_size: 104857600
  grpc_server_max_concurrent_streams: 1000

# The distributor_config configures the Cortex distributor.
distributor:
  shard_by_all_labels: true
  pool:
    health_check_ingesters: true
  
  ha_tracker:
    # Enable the distributors HA tracker so that it can accept samples from
    # Prometheus HA replicas gracefully (requires labels).
    # CLI flag: -distributor.ha-tracker.enable
    enable_ha_tracker: true

    # Backend storage to use for the ring. Please be aware that memberlist is not
    # supported by the HA tracker since gossip propagation is too slow for HA
    # purposes.
    kvstore:
      #  The consul_config configures the consul client.
      # The CLI flags prefix for this block config is: distributor.ha-tracker
      store: "consul"
      # The prefix for the keys in the store. Should end with a /.
      # CLI flag: -distributor.ha-tracker.prefix
      prefix: "ha-tracker/distributor/"
      # The consul_config configures the consul client.
      # The CLI flags prefix for this block config is: distributor.ring
      consul:
        # Hostname and port of Consul.
        # CLI flag: -<prefix>.consul.hostname
        host: "192.168.56.101:8500"
  
  ring:
    kvstore:
      # Backend storage to use for the ring. Supported values are: consul, etcd,
      # inmemory, memberlist, multi.
      # CLI flag: -distributor.ring.store
      store: "consul"
      # The prefix for the keys in the store. Should end with a /.
      # CLI flag: -distributor.ring.prefix
      prefix: "collectors/distributor/"
      # The consul_config configures the consul client.
      # The CLI flags prefix for this block config is: distributor.ring
      consul:
        # Hostname and port of Consul.
        # CLI flag: -<prefix>.consul.hostname
        host: "192.168.56.101:8500"

# The ingester_client_config configures how the Cortex distributors connect to the ingesters.
ingester_client:
  grpc_client_config:
    # Configure the client to allow messages up to 100MB.
    max_recv_msg_size: 104857600
    max_send_msg_size: 104857600
    grpc_compression: gzip

# The ingester_config configures the Cortex ingester.
ingester:
  
  # Configures the Write-Ahead Log (WAL) for the Cortex chunks storage. This
  # config is ignored when running the Cortex blocks storage.
  walconfig:
    # Enable writing of ingested data into WAL.
    # CLI flag: -ingester.wal-enabled
    wal_enabled: false
  
  lifecycler:
    # The address to advertise for this ingester.  Will be autodiscovered by
    # looking up address on eth0 or en0; can be specified if this fails.
    # address: 127.0.0.1

    # We want to start immediately and flush on shutdown.
    join_after: 5s
    min_ready_duration: 0s
    final_sleep: 0s
    num_tokens: 512

    # Use an in memory ring store, so we don't need to launch a Consul.
    ring:
      kvstore:
        store: consul
        # The consul_config configures the consul client.
        
        # The prefix for the keys in the store. Should end with a /.
        # CLI flag: -ring.prefix
        prefix: "collectors/ingester/"

        consul:
          # Hostname and port of Consul.
          # CLI flag: -<prefix>.consul.hostname
          host: 192.168.56.101:8500
      # The number of ingesters to write to and read from.
      # CLI flag: -distributor.replication-factor
      replication_factor: 2

      # True to enable the zone-awareness and replicate ingested samples across
      # different availability zones.
      # CLI flag: -distributor.zone-awareness-enabled
      zone_awareness_enabled: true